services:
  - type: web
    name: college-portal-scraper-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: "8000"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: demo-usingfastapi
      - key: API_USERNAME
        sync: false
      - key: API_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true
