services:
  - type: web
    name: college-portal-scraper-backend
    env: python
    plan: free
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt

      # Install Playwright and browsers
      chmod +x install_playwright.sh && ./install_playwright.sh

      # Run debug scripts
      chmod +x test_playwright.py && python test_playwright.py
      chmod +x find_chrome.py && python find_chrome.py
      chmod +x debug_chrome.py && python debug_chrome.py
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:$PORT --timeout 300 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: demo-usingfastapi
      - key: API_USERNAME
        sync: false
      - key: API_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true
